services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
      - brain
    networks:
      - ducketa_network

  brain:
    build: ./brain
    ports:
      - "5500:5500"
    depends_on:
      - postgres
    networks:
      - ducketa_network

  postgres:
    image: postgres:15
    container_name: ducketa_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ducketa_network

networks:
  ducketa_network:

volumes:
  pgdata: