spring:
  application:
    name: DuckETA

  datasource:
    url: jdbc:postgresql://localhost:5432/DuckETA
    username: postgres
    password: kauan123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true